### ISSUE TITLE
Helmchart not working

### ISSUE THREAD

**Issue by danjo133** [pceric/kafka-offset-lag-for-prometheus#16]
Hi,

The file is in /, not /go/bin/

https://github.com/pceric/kafka-offset-lag-for-prometheus/blob/eadf19e838c1eae71f440970385fcfe9b996ce4c/charts/kafka-offset-lag-for-prometheus/templates/deployment.yaml#L31

**Comment by pceric** [comment]
Thanks for the report. Should be fixed now.
