### ISSUE TITLE
kubernetes 1.16 breaking changes

### ISSUE THREAD

**Issue by danjo133** [pceric/kafka-offset-lag-for-prometheus#17]
Hi,

Kubernetes 1.16 deprecates network policies under extension, the way forward is with apiVersion below:
apiVersion: networking.k8s.io/v1

https://github.com/pceric/kafka-offset-lag-for-prometheus/blob/eadf19e838c1eae71f440970385fcfe9b996ce4c/charts/kafka-offset-lag-for-prometheus/templates/networkpolicy.yaml#L2

**Comment by pceric** [comment]
Should also be fixed now.
